#!/usr/bin/env python

env = Environment (F08="gfortran",
                   F08FLAGS="-fbacktrace -Wall -g")
example = []
for i in range(1, 4):
    example += env.Program ("example{}".format(i), "example{}.f08".format(i))

example += env.Program ("example7", "example7.f08")
example += env.Program ("example46", "example46.f08")
